### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by nobodyyu** [thedejifab/flutter_auth0#1]
Hi  I finished setting in url_utils.dart and try to login then I got crash with logs

Do you have same experience of this situation?

** First throw call stack:
(
	0   CoreFoundation                      0x000000010572b1bb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x0000000104cc9735 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010572b015 +[NSException raise:format:] + 197
	3   SafariServices                      0x0000000105bee356 -[SFSafariViewController initWithURL:configuration:] + 107
	4   SafariServices                      0x0000000105bee900 -[SFSafariViewController initWithURL:] + 94
	5   Runner                              0x0000000102e298c8 -[FLTUrlLauncherPlugin launchURLInVC:result:] + 152
	6   Runner                              0x0000000102e29094 -[FLTUrlLauncherPlugin handleMethodCall:result:] + 996
	7   Flutter                             0x0000000102ed79a2 __45-[FlutterMethodChannel setMetho<…>
Lost connection to device.
Exited (sigterm)

**Comment by thedejifab** [comment]
@nobodyyu Are you trying to run on iOS? As it stands, this codebase only supports running on Android. I was unable to test for iOS since I don't run on a MacBook. 
It'll be better if you can provide more details such as the last action that was triggered before the crash and check if you inputted the correct details in the url_utils.dart file

**Comment by nobodyyu** [comment]
Hi @thedejifab , yes I'm using iOS, and after I tested all the scenarios, I've found that cash root cause is there is a space " " in URL in url_launcher, eg. in scope - "openid profile email offline_access" will make url_launcher crash.  you may close the issue and I'll try to fix url_launcher's problem

**Comment by thedejifab** [comment]
Oh oh. Glad you fixed it. I'll close the issue but feel free to reopen whenever the crash reoccurs. I fear you might encounter some issue with deeplinking into the app after the authorization process though, as I did not add the callback URL in the iOS equivalent of AndroidManifest,xml. Let me know how the process goes on your end
